#マップの中心地点と半径を指定
MAP:
  Center:
    x: 0
    z: 0
  Radius: 1000
  Height: 0
#変性ボーダーの待機時間(sTime)と収縮時間(vTime)とラウンド終了時の半径(Radius)と範囲外ダメージの指定。(秒)
Ring:
  1:
    sTime: 90
    vTime: 180
    Radius: 500
    Damage: 0.1
  2:
    sTime: 120
    vTime: 45
    Radius: 300
    Damage: 0.1
  3:
    sTime: 165
    vTime: 45
    Radius: 175
    Damage: 0.8
  4:
    sTime: 135
    vTime: 40
    Radius: 100
    Damage: 1.8
  5:
    sTime: 90
    vTime: 40
    Radius: 50
    Damage: 2.9
  6:
    sTime: 60
    vTime: 120
    Radius: 20
    Damage: 2.9
  Times: 6
  #最終ボーダーの位置を(x z)の書式で指定
  LastCenter:
    - 254 -287
    - 431 43
    - 284 -91
    - 451 -147
    - -52 -398
    - 259 -4
    - 197 284
    - 23 -425
    - 167 197
    - 281 -334
    - 236 257
    - 115 -230
    - -13 -142
    - -40 -306
    - 207 334
    - -207 -254
    - -75 430
    - -331 -346
    - 38 220
    - -194 -332
    - 161 71
    - -100 250
    - -233 129
    - -385 -171
    - -164 339
    - -352 20
    - -382 259
    - -314 82
    - -335 29
    - -397 221
    - -224 57
    - -301 272
#実行するワールドを指定
World: world
#ハイティアのルートテーブルを指定
HighTierLootTable: battleroyale2:chest/ver10