name: BattleRoyaleCore3.0
version: '${project.version}'
main: jp.houlab.mochidsuki.battleroyalecore3.Main
api-version: '1.20'

softdepend: [ProtocolLib ]

commands:
  brc:
    aliases: [battleroyalecore]
    description: BRC管理コマンド
    permission: battleroyalecore30.command.brg
    permission-message: Permission denied
    usage: gr reload